/* eslint-disable */
/*
 * 자동 생성 파일 — 직접 수정하지 마세요.
 * data/*.csv 를 고친 뒤 `python tools/build_data.py` 로 다시 생성합니다.
 */
const CLIMATE_DATA = {
  "meta": {
    "scenario": "SSP1-2.6",
    "observedScenario": "현재기후",
    "humidityScenario": "SSP2-4.5",
    "decades": [
      2000,
      2010,
      2020,
      2030,
      2040,
      2050,
      2060,
      2070,
      2080,
      2090
    ],
    "observedDecades": [
      2000,
      2010
    ],
    "baseDecade": 2000,
    "source": "기상청 기후변화 시나리오(SSP) 남한 상세 전망",
    "sourceFiles": [
      "air temperature.csv",
      "heat wave.csv",
      "Temperature.csv",
      "Humidity.csv",
      "CO2.csv"
    ]
  },
  "regions": [
    {
      "id": "전국",
      "label": "전국",
      "short": "전국",
      "slug": "nationwide",
      "lon": 127.8,
      "lat": 36.4,
      "hasSummerFelt": true,
      "series": [
        {
          "decade": 2000,
          "scenario": "현재기후",
          "observed": true,
          "temp": 11.9,
          "heatDays": 8.3,
          "tropicalNights": 2.7,
          "feltYear": 6.0,
          "feltSummer": 29.8,
          "feltWinter": -3.6,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null
        },
        {
          "decade": 2010,
          "scenario": "현재기후",
          "observed": true,
          "temp": 11.9,
          "heatDays": 9.3,
          "tropicalNights": 3.7,
          "feltYear": 6.0,
          "feltSummer": 30.5,
          "feltWinter": -4.1,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null
        },
        {
          "decade": 2020,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.0,
          "heatDays": 15.3,
          "tropicalNights": 13.7,
          "feltYear": 7.3,
          "feltSummer": 31.4,
          "feltWinter": -2.9,
          "absHumidity": 7.81,
          "relHumidity": 68.9,
          "co2": 414.0
        },
        {
          "decade": 2030,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.4,
          "heatDays": 18.2,
          "tropicalNights": 17.7,
          "feltYear": 7.7,
          "feltSummer": 31.8,
          "feltWinter": -2.0,
          "absHumidity": 7.8,
          "relHumidity": 67.1,
          "co2": 440.0
        },
        {
          "decade": 2040,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.5,
          "heatDays": 22.8,
          "tropicalNights": 22.5,
          "feltYear": 7.9,
          "feltSummer": 32.4,
          "feltWinter": -2.5,
          "absHumidity": 8.26,
          "relHumidity": 70.7,
          "co2": 458.0
        },
        {
          "decade": 2050,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.5,
          "heatDays": 21.1,
          "tropicalNights": 20.4,
          "feltYear": 7.9,
          "feltSummer": 32.3,
          "feltWinter": -2.7,
          "absHumidity": 8.41,
          "relHumidity": 71.9,
          "co2": 469.0
        },
        {
          "decade": 2060,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.9,
          "heatDays": 22.2,
          "tropicalNights": 21.2,
          "feltYear": 8.4,
          "feltSummer": 32.4,
          "feltWinter": -1.9,
          "absHumidity": 8.71,
          "relHumidity": 72.7,
          "co2": 474.0
        },
        {
          "decade": 2070,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.0,
          "heatDays": 22.2,
          "tropicalNights": 20.3,
          "feltYear": 8.4,
          "feltSummer": 32.5,
          "feltWinter": -1.9,
          "absHumidity": 8.72,
          "relHumidity": 72.3,
          "co2": 473.0
        },
        {
          "decade": 2080,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.1,
          "heatDays": 26.0,
          "tropicalNights": 25.9,
          "feltYear": 8.6,
          "feltSummer": 32.9,
          "feltWinter": -1.6,
          "absHumidity": 9.1,
          "relHumidity": 75.0,
          "co2": 467.0
        },
        {
          "decade": 2090,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.3,
          "heatDays": 22.3,
          "tropicalNights": 18.7,
          "feltYear": 8.7,
          "feltSummer": 32.6,
          "feltWinter": -1.0,
          "absHumidity": 9.12,
          "relHumidity": 74.3,
          "co2": 457.0
        }
      ]
    },
    {
      "id": "서울특별시",
      "label": "서울특별시",
      "short": "서울",
      "slug": "seoul",
      "lon": 126.98,
      "lat": 37.57,
      "hasSummerFelt": true,
      "series": [
        {
          "decade": 2000,
          "scenario": "현재기후",
          "observed": true,
          "temp": 13.2,
          "heatDays": 13.3,
          "tropicalNights": 8.6,
          "feltYear": 6.6,
          "feltSummer": 30.2,
          "feltWinter": -3.9,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null
        },
        {
          "decade": 2010,
          "scenario": "현재기후",
          "observed": true,
          "temp": 13.1,
          "heatDays": 16.8,
          "tropicalNights": 14.0,
          "feltYear": 6.6,
          "feltSummer": 30.8,
          "feltWinter": -4.3,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null
        },
        {
          "decade": 2020,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.4,
          "heatDays": 28.8,
          "tropicalNights": 31.2,
          "feltYear": 8.0,
          "feltSummer": 31.8,
          "feltWinter": -3.0,
          "absHumidity": 8.03,
          "relHumidity": 65.0,
          "co2": 414.0
        },
        {
          "decade": 2030,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.7,
          "heatDays": 32.8,
          "tropicalNights": 36.4,
          "feltYear": 8.4,
          "feltSummer": 32.2,
          "feltWinter": -2.1,
          "absHumidity": 7.93,
          "relHumidity": 63.0,
          "co2": 440.0
        },
        {
          "decade": 2040,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.8,
          "heatDays": 38.5,
          "tropicalNights": 40.9,
          "feltYear": 8.6,
          "feltSummer": 32.7,
          "feltWinter": -2.6,
          "absHumidity": 8.43,
          "relHumidity": 66.6,
          "co2": 458.0
        },
        {
          "decade": 2050,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.8,
          "heatDays": 36.6,
          "tropicalNights": 38.8,
          "feltYear": 8.5,
          "feltSummer": 32.7,
          "feltWinter": -3.0,
          "absHumidity": 8.6,
          "relHumidity": 67.9,
          "co2": 469.0
        },
        {
          "decade": 2060,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.2,
          "heatDays": 40.0,
          "tropicalNights": 41.0,
          "feltYear": 9.1,
          "feltSummer": 32.7,
          "feltWinter": -2.0,
          "absHumidity": 8.9,
          "relHumidity": 68.6,
          "co2": 474.0
        },
        {
          "decade": 2070,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.3,
          "heatDays": 41.1,
          "tropicalNights": 41.5,
          "feltYear": 9.2,
          "feltSummer": 32.9,
          "feltWinter": -2.1,
          "absHumidity": 8.96,
          "relHumidity": 68.7,
          "co2": 473.0
        },
        {
          "decade": 2080,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.4,
          "heatDays": 43.9,
          "tropicalNights": 45.6,
          "feltYear": 9.3,
          "feltSummer": 33.2,
          "feltWinter": -1.7,
          "absHumidity": 9.36,
          "relHumidity": 71.3,
          "co2": 467.0
        },
        {
          "decade": 2090,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.6,
          "heatDays": 41.5,
          "tropicalNights": 37.7,
          "feltYear": 9.4,
          "feltSummer": 32.9,
          "feltWinter": -1.0,
          "absHumidity": 9.4,
          "relHumidity": 70.7,
          "co2": 457.0
        }
      ]
    },
    {
      "id": "부산광역시",
      "label": "부산광역시",
      "short": "부산",
      "slug": "busan",
      "lon": 129.08,
      "lat": 35.18,
      "hasSummerFelt": true,
      "series": [
        {
          "decade": 2000,
          "scenario": "현재기후",
          "observed": true,
          "temp": 14.6,
          "heatDays": 7.5,
          "tropicalNights": 9.6,
          "feltYear": 8.0,
          "feltSummer": 29.1,
          "feltWinter": -0.9,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null
        },
        {
          "decade": 2010,
          "scenario": "현재기후",
          "observed": true,
          "temp": 14.6,
          "heatDays": 8.3,
          "tropicalNights": 16.1,
          "feltYear": 8.3,
          "feltSummer": 29.6,
          "feltWinter": -1.2,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null
        },
        {
          "decade": 2020,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.6,
          "heatDays": 14.0,
          "tropicalNights": 29.0,
          "feltYear": 9.4,
          "feltSummer": 30.6,
          "feltWinter": 0.3,
          "absHumidity": 8.59,
          "relHumidity": 64.6,
          "co2": 414.0
        },
        {
          "decade": 2030,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.0,
          "heatDays": 17.0,
          "tropicalNights": 34.9,
          "feltYear": 9.8,
          "feltSummer": 31.0,
          "feltWinter": 1.2,
          "absHumidity": 8.59,
          "relHumidity": 63.1,
          "co2": 440.0
        },
        {
          "decade": 2040,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.2,
          "heatDays": 21.6,
          "tropicalNights": 39.8,
          "feltYear": 10.1,
          "feltSummer": 31.6,
          "feltWinter": 0.7,
          "absHumidity": 9.04,
          "relHumidity": 65.6,
          "co2": 458.0
        },
        {
          "decade": 2050,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.2,
          "heatDays": 19.5,
          "tropicalNights": 38.4,
          "feltYear": 10.0,
          "feltSummer": 31.5,
          "feltWinter": 0.5,
          "absHumidity": 9.3,
          "relHumidity": 67.5,
          "co2": 469.0
        },
        {
          "decade": 2060,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.5,
          "heatDays": 19.9,
          "tropicalNights": 38.8,
          "feltYear": 10.4,
          "feltSummer": 31.5,
          "feltWinter": 1.2,
          "absHumidity": 9.57,
          "relHumidity": 68.2,
          "co2": 474.0
        },
        {
          "decade": 2070,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.6,
          "heatDays": 19.8,
          "tropicalNights": 39.6,
          "feltYear": 10.5,
          "feltSummer": 31.7,
          "feltWinter": 1.2,
          "absHumidity": 9.54,
          "relHumidity": 67.6,
          "co2": 473.0
        },
        {
          "decade": 2080,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.8,
          "heatDays": 25.4,
          "tropicalNights": 46.4,
          "feltYear": 10.7,
          "feltSummer": 32.1,
          "feltWinter": 1.6,
          "absHumidity": 9.95,
          "relHumidity": 69.6,
          "co2": 467.0
        },
        {
          "decade": 2090,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.9,
          "heatDays": 18.1,
          "tropicalNights": 37.0,
          "feltYear": 10.8,
          "feltSummer": 31.6,
          "feltWinter": 2.3,
          "absHumidity": 9.94,
          "relHumidity": 69.1,
          "co2": 457.0
        }
      ]
    },
    {
      "id": "대전광역시",
      "label": "대전광역시",
      "short": "대전",
      "slug": "daejeon",
      "lon": 127.38,
      "lat": 36.35,
      "hasSummerFelt": true,
      "series": [
        {
          "decade": 2000,
          "scenario": "현재기후",
          "observed": true,
          "temp": 13.0,
          "heatDays": 15.6,
          "tropicalNights": 2.9,
          "feltYear": 5.7,
          "feltSummer": 30.3,
          "feltWinter": -3.9,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null
        },
        {
          "decade": 2010,
          "scenario": "현재기후",
          "observed": true,
          "temp": 12.8,
          "heatDays": 18.3,
          "tropicalNights": 7.1,
          "feltYear": 5.8,
          "feltSummer": 31.1,
          "feltWinter": -4.2,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null
        },
        {
          "decade": 2020,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.1,
          "heatDays": 32.3,
          "tropicalNights": 25.8,
          "feltYear": 7.0,
          "feltSummer": 32.0,
          "feltWinter": -3.4,
          "absHumidity": 8.28,
          "relHumidity": 68.3,
          "co2": 414.0
        },
        {
          "decade": 2030,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.4,
          "heatDays": 35.3,
          "tropicalNights": 31.1,
          "feltYear": 7.4,
          "feltSummer": 32.4,
          "feltWinter": -2.6,
          "absHumidity": 8.26,
          "relHumidity": 66.9,
          "co2": 440.0
        },
        {
          "decade": 2040,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.5,
          "heatDays": 42.4,
          "tropicalNights": 36.2,
          "feltYear": 7.6,
          "feltSummer": 33.0,
          "feltWinter": -3.1,
          "absHumidity": 8.73,
          "relHumidity": 70.2,
          "co2": 458.0
        },
        {
          "decade": 2050,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.6,
          "heatDays": 39.4,
          "tropicalNights": 34.1,
          "feltYear": 7.6,
          "feltSummer": 32.9,
          "feltWinter": -3.2,
          "absHumidity": 8.9,
          "relHumidity": 71.2,
          "co2": 469.0
        },
        {
          "decade": 2060,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.9,
          "heatDays": 42.8,
          "tropicalNights": 34.7,
          "feltYear": 8.1,
          "feltSummer": 33.0,
          "feltWinter": -2.4,
          "absHumidity": 9.22,
          "relHumidity": 72.4,
          "co2": 474.0
        },
        {
          "decade": 2070,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.0,
          "heatDays": 43.3,
          "tropicalNights": 33.0,
          "feltYear": 8.1,
          "feltSummer": 33.1,
          "feltWinter": -2.5,
          "absHumidity": 9.23,
          "relHumidity": 72.0,
          "co2": 473.0
        },
        {
          "decade": 2080,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.2,
          "heatDays": 48.4,
          "tropicalNights": 39.9,
          "feltYear": 8.3,
          "feltSummer": 33.5,
          "feltWinter": -2.2,
          "absHumidity": 9.61,
          "relHumidity": 74.1,
          "co2": 467.0
        },
        {
          "decade": 2090,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.3,
          "heatDays": 45.3,
          "tropicalNights": 31.5,
          "feltYear": 8.3,
          "feltSummer": 33.2,
          "feltWinter": -1.6,
          "absHumidity": 9.66,
          "relHumidity": 74.0,
          "co2": 457.0
        }
      ]
    },
    {
      "id": "강원 속초시",
      "label": "강원 속초시",
      "short": "속초",
      "slug": "sokcho",
      "lon": 128.59,
      "lat": 38.21,
      "hasSummerFelt": true,
      "series": [
        {
          "decade": 2000,
          "scenario": "현재기후",
          "observed": true,
          "temp": 12.4,
          "heatDays": 5.2,
          "tropicalNights": 2.8,
          "feltYear": 5.4,
          "feltSummer": 27.2,
          "feltWinter": -4.3,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null
        },
        {
          "decade": 2010,
          "scenario": "현재기후",
          "observed": true,
          "temp": 12.6,
          "heatDays": 8.4,
          "tropicalNights": 6.1,
          "feltYear": 6.1,
          "feltSummer": 28.2,
          "feltWinter": -3.9,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null
        },
        {
          "decade": 2020,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.6,
          "heatDays": 7.5,
          "tropicalNights": 11.7,
          "feltYear": 7.0,
          "feltSummer": 29.0,
          "feltWinter": -2.8,
          "absHumidity": 7.58,
          "relHumidity": 64.4,
          "co2": 414.0
        },
        {
          "decade": 2030,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.1,
          "heatDays": 7.6,
          "tropicalNights": 15.4,
          "feltYear": 7.5,
          "feltSummer": 29.4,
          "feltWinter": -1.9,
          "absHumidity": 7.51,
          "relHumidity": 61.9,
          "co2": 440.0
        },
        {
          "decade": 2040,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.2,
          "heatDays": 11.8,
          "tropicalNights": 21.5,
          "feltYear": 7.6,
          "feltSummer": 29.9,
          "feltWinter": -2.4,
          "absHumidity": 8.06,
          "relHumidity": 66.0,
          "co2": 458.0
        },
        {
          "decade": 2050,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.1,
          "heatDays": 9.4,
          "tropicalNights": 16.8,
          "feltYear": 7.5,
          "feltSummer": 29.9,
          "feltWinter": -2.7,
          "absHumidity": 8.15,
          "relHumidity": 67.2,
          "co2": 469.0
        },
        {
          "decade": 2060,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.5,
          "heatDays": 9.4,
          "tropicalNights": 18.6,
          "feltYear": 8.1,
          "feltSummer": 30.0,
          "feltWinter": -1.9,
          "absHumidity": 8.46,
          "relHumidity": 68.1,
          "co2": 474.0
        },
        {
          "decade": 2070,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.7,
          "heatDays": 8.3,
          "tropicalNights": 16.9,
          "feltYear": 8.3,
          "feltSummer": 30.1,
          "feltWinter": -1.8,
          "absHumidity": 8.44,
          "relHumidity": 67.1,
          "co2": 473.0
        },
        {
          "decade": 2080,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.8,
          "heatDays": 13.3,
          "tropicalNights": 24.7,
          "feltYear": 8.3,
          "feltSummer": 30.5,
          "feltWinter": -1.6,
          "absHumidity": 8.77,
          "relHumidity": 69.3,
          "co2": 467.0
        },
        {
          "decade": 2090,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.9,
          "heatDays": 6.8,
          "tropicalNights": 14.0,
          "feltYear": 8.5,
          "feltSummer": 29.9,
          "feltWinter": -0.8,
          "absHumidity": 8.83,
          "relHumidity": 69.3,
          "co2": 457.0
        }
      ]
    },
    {
      "id": "충청남도 천안시",
      "label": "충청남도 천안시",
      "short": "천안",
      "slug": "cheonan",
      "lon": 127.15,
      "lat": 36.82,
      "hasSummerFelt": false,
      "series": [
        {
          "decade": 2000,
          "scenario": "현재기후",
          "observed": true,
          "temp": 12.0,
          "heatDays": 10.0,
          "tropicalNights": 0.8,
          "feltYear": 4.5,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null,
          "note": "이미지 추정값"
        },
        {
          "decade": 2010,
          "scenario": "현재기후",
          "observed": true,
          "temp": 12.3,
          "heatDays": 16.5,
          "tropicalNights": 4.2,
          "feltYear": 4.9,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null,
          "note": "이미지 추정값"
        },
        {
          "decade": 2020,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.3,
          "heatDays": 28.4,
          "tropicalNights": 21.2,
          "feltYear": 6.0,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": 7.98,
          "relHumidity": 69.1,
          "co2": 414.0,
          "note": "이미지 추정값"
        },
        {
          "decade": 2030,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.7,
          "heatDays": 31.1,
          "tropicalNights": 25.4,
          "feltYear": 6.4,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": 7.95,
          "relHumidity": 67.2,
          "co2": 440.0,
          "note": "이미지 추정값"
        },
        {
          "decade": 2040,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.8,
          "heatDays": 37.9,
          "tropicalNights": 31.0,
          "feltYear": 6.5,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": 8.42,
          "relHumidity": 70.7,
          "co2": 458.0,
          "note": "이미지 추정값"
        },
        {
          "decade": 2050,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.7,
          "heatDays": 35.3,
          "tropicalNights": 28.4,
          "feltYear": 6.5,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": 8.55,
          "relHumidity": 72.2,
          "co2": 469.0,
          "note": "이미지 추정값"
        },
        {
          "decade": 2060,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.2,
          "heatDays": 38.5,
          "tropicalNights": 28.6,
          "feltYear": 7.0,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": 8.87,
          "relHumidity": 72.7,
          "co2": 474.0,
          "note": "이미지 추정값"
        },
        {
          "decade": 2070,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.3,
          "heatDays": 39.2,
          "tropicalNights": 27.0,
          "feltYear": 7.0,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": 8.94,
          "relHumidity": 72.8,
          "co2": 473.0,
          "note": "이미지 추정값"
        },
        {
          "decade": 2080,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.4,
          "heatDays": 42.8,
          "tropicalNights": 33.8,
          "feltYear": 7.3,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": 9.28,
          "relHumidity": 75.1,
          "co2": 467.0,
          "note": "이미지 추정값"
        },
        {
          "decade": 2090,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.5,
          "heatDays": 40.1,
          "tropicalNights": 25.4,
          "feltYear": 7.3,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": 9.32,
          "relHumidity": 75.0,
          "co2": 457.0,
          "note": "이미지 추정값"
        }
      ]
    }
  ]
};

if (typeof module !== "undefined" && module.exports) {
    module.exports = CLIMATE_DATA;
}
