/* eslint-disable */
/* tools/build_search_data.py로 생성한 우리 지역 보기 전용 데이터 */
const SEARCH_DATA = {
  "meta": {
    "scenario": "SSP1-2.6",
    "observedScenario": "현재기후",
    "decades": [
      2000,
      2010,
      2020,
      2030,
      2040,
      2050,
      2060,
      2070,
      2080,
      2090
    ],
    "observedDecades": [
      2000,
      2010
    ],
    "baseDecade": 2000,
    "source": "우리 지역 보기 전용 통합지표",
    "sourceFiles": [
      "광주광역시_SSP시나리오_통합지표_연대별.csv",
      "대구광역시_SSP시나리오_통합지표_연대별 (2).csv",
      "대전광역시_SSP시나리오_통합지표_연대별.csv",
      "세종특별자치시_SSP시나리오_통합지표_연대별.csv",
      "울산광역시_SSP시나리오_통합지표_연대별.csv",
      "인천광역시_SSP시나리오_통합지표_연대별.csv",
      "제주특별자치도_SSP시나리오_통합지표_연대별.csv"
    ]
  },
  "regions": [
    {
      "id": "전국",
      "label": "전국",
      "short": "전국",
      "slug": "nationwide",
      "lon": 127.8,
      "lat": 36.4,
      "hasSummerFelt": true,
      "series": [
        {
          "decade": 2000,
          "scenario": "현재기후",
          "observed": true,
          "temp": 11.9,
          "heatDays": 8.3,
          "tropicalNights": 2.7,
          "feltYear": 6.0,
          "feltSummer": 29.8,
          "feltWinter": -3.6,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null
        },
        {
          "decade": 2010,
          "scenario": "현재기후",
          "observed": true,
          "temp": 11.9,
          "heatDays": 9.3,
          "tropicalNights": 3.7,
          "feltYear": 6.0,
          "feltSummer": 30.5,
          "feltWinter": -4.1,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null
        },
        {
          "decade": 2020,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.0,
          "heatDays": 15.3,
          "tropicalNights": 13.7,
          "feltYear": 7.3,
          "feltSummer": 31.4,
          "feltWinter": -2.9,
          "absHumidity": 7.81,
          "relHumidity": 68.9,
          "co2": 414.0
        },
        {
          "decade": 2030,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.4,
          "heatDays": 18.2,
          "tropicalNights": 17.7,
          "feltYear": 7.7,
          "feltSummer": 31.8,
          "feltWinter": -2.0,
          "absHumidity": 7.8,
          "relHumidity": 67.1,
          "co2": 440.0
        },
        {
          "decade": 2040,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.5,
          "heatDays": 22.8,
          "tropicalNights": 22.5,
          "feltYear": 7.9,
          "feltSummer": 32.4,
          "feltWinter": -2.5,
          "absHumidity": 8.26,
          "relHumidity": 70.7,
          "co2": 458.0
        },
        {
          "decade": 2050,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.5,
          "heatDays": 21.1,
          "tropicalNights": 20.4,
          "feltYear": 7.9,
          "feltSummer": 32.3,
          "feltWinter": -2.7,
          "absHumidity": 8.41,
          "relHumidity": 71.9,
          "co2": 469.0
        },
        {
          "decade": 2060,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.9,
          "heatDays": 22.2,
          "tropicalNights": 21.2,
          "feltYear": 8.4,
          "feltSummer": 32.4,
          "feltWinter": -1.9,
          "absHumidity": 8.71,
          "relHumidity": 72.7,
          "co2": 474.0
        },
        {
          "decade": 2070,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.0,
          "heatDays": 22.2,
          "tropicalNights": 20.3,
          "feltYear": 8.4,
          "feltSummer": 32.5,
          "feltWinter": -1.9,
          "absHumidity": 8.72,
          "relHumidity": 72.3,
          "co2": 473.0
        },
        {
          "decade": 2080,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.1,
          "heatDays": 26.0,
          "tropicalNights": 25.9,
          "feltYear": 8.6,
          "feltSummer": 32.9,
          "feltWinter": -1.6,
          "absHumidity": 9.1,
          "relHumidity": 75.0,
          "co2": 467.0
        },
        {
          "decade": 2090,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.3,
          "heatDays": 22.3,
          "tropicalNights": 18.7,
          "feltYear": 8.7,
          "feltSummer": 32.6,
          "feltWinter": -1.0,
          "absHumidity": 9.12,
          "relHumidity": 74.3,
          "co2": 457.0
        }
      ]
    },
    {
      "id": "서울특별시",
      "label": "서울특별시",
      "short": "서울",
      "slug": "seoul",
      "lon": 126.98,
      "lat": 37.57,
      "hasSummerFelt": true,
      "series": [
        {
          "decade": 2000,
          "scenario": "현재기후",
          "observed": true,
          "temp": 13.2,
          "heatDays": 13.3,
          "tropicalNights": 8.6,
          "feltYear": 6.6,
          "feltSummer": 30.2,
          "feltWinter": -3.9,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null
        },
        {
          "decade": 2010,
          "scenario": "현재기후",
          "observed": true,
          "temp": 13.1,
          "heatDays": 16.8,
          "tropicalNights": 14.0,
          "feltYear": 6.6,
          "feltSummer": 30.8,
          "feltWinter": -4.3,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null
        },
        {
          "decade": 2020,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.4,
          "heatDays": 28.8,
          "tropicalNights": 31.2,
          "feltYear": 8.0,
          "feltSummer": 31.8,
          "feltWinter": -3.0,
          "absHumidity": 8.03,
          "relHumidity": 65.0,
          "co2": 414.0
        },
        {
          "decade": 2030,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.7,
          "heatDays": 32.8,
          "tropicalNights": 36.4,
          "feltYear": 8.4,
          "feltSummer": 32.2,
          "feltWinter": -2.1,
          "absHumidity": 7.93,
          "relHumidity": 63.0,
          "co2": 440.0
        },
        {
          "decade": 2040,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.8,
          "heatDays": 38.5,
          "tropicalNights": 40.9,
          "feltYear": 8.6,
          "feltSummer": 32.7,
          "feltWinter": -2.6,
          "absHumidity": 8.43,
          "relHumidity": 66.6,
          "co2": 458.0
        },
        {
          "decade": 2050,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.8,
          "heatDays": 36.6,
          "tropicalNights": 38.8,
          "feltYear": 8.5,
          "feltSummer": 32.7,
          "feltWinter": -3.0,
          "absHumidity": 8.6,
          "relHumidity": 67.9,
          "co2": 469.0
        },
        {
          "decade": 2060,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.2,
          "heatDays": 40.0,
          "tropicalNights": 41.0,
          "feltYear": 9.1,
          "feltSummer": 32.7,
          "feltWinter": -2.0,
          "absHumidity": 8.9,
          "relHumidity": 68.6,
          "co2": 474.0
        },
        {
          "decade": 2070,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.3,
          "heatDays": 41.1,
          "tropicalNights": 41.5,
          "feltYear": 9.2,
          "feltSummer": 32.9,
          "feltWinter": -2.1,
          "absHumidity": 8.96,
          "relHumidity": 68.7,
          "co2": 473.0
        },
        {
          "decade": 2080,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.4,
          "heatDays": 43.9,
          "tropicalNights": 45.6,
          "feltYear": 9.3,
          "feltSummer": 33.2,
          "feltWinter": -1.7,
          "absHumidity": 9.36,
          "relHumidity": 71.3,
          "co2": 467.0
        },
        {
          "decade": 2090,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.6,
          "heatDays": 41.5,
          "tropicalNights": 37.7,
          "feltYear": 9.4,
          "feltSummer": 32.9,
          "feltWinter": -1.0,
          "absHumidity": 9.4,
          "relHumidity": 70.7,
          "co2": 457.0
        }
      ]
    },
    {
      "id": "부산광역시",
      "label": "부산광역시",
      "short": "부산",
      "slug": "busan",
      "lon": 129.08,
      "lat": 35.18,
      "hasSummerFelt": true,
      "series": [
        {
          "decade": 2000,
          "scenario": "현재기후",
          "observed": true,
          "temp": 14.6,
          "heatDays": 7.5,
          "tropicalNights": 9.6,
          "feltYear": 8.0,
          "feltSummer": 29.1,
          "feltWinter": -0.9,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null
        },
        {
          "decade": 2010,
          "scenario": "현재기후",
          "observed": true,
          "temp": 14.6,
          "heatDays": 8.3,
          "tropicalNights": 16.1,
          "feltYear": 8.3,
          "feltSummer": 29.6,
          "feltWinter": -1.2,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null
        },
        {
          "decade": 2020,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.6,
          "heatDays": 14.0,
          "tropicalNights": 29.0,
          "feltYear": 9.4,
          "feltSummer": 30.6,
          "feltWinter": 0.3,
          "absHumidity": 8.59,
          "relHumidity": 64.6,
          "co2": 414.0
        },
        {
          "decade": 2030,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.0,
          "heatDays": 17.0,
          "tropicalNights": 34.9,
          "feltYear": 9.8,
          "feltSummer": 31.0,
          "feltWinter": 1.2,
          "absHumidity": 8.59,
          "relHumidity": 63.1,
          "co2": 440.0
        },
        {
          "decade": 2040,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.2,
          "heatDays": 21.6,
          "tropicalNights": 39.8,
          "feltYear": 10.1,
          "feltSummer": 31.6,
          "feltWinter": 0.7,
          "absHumidity": 9.04,
          "relHumidity": 65.6,
          "co2": 458.0
        },
        {
          "decade": 2050,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.2,
          "heatDays": 19.5,
          "tropicalNights": 38.4,
          "feltYear": 10.0,
          "feltSummer": 31.5,
          "feltWinter": 0.5,
          "absHumidity": 9.3,
          "relHumidity": 67.5,
          "co2": 469.0
        },
        {
          "decade": 2060,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.5,
          "heatDays": 19.9,
          "tropicalNights": 38.8,
          "feltYear": 10.4,
          "feltSummer": 31.5,
          "feltWinter": 1.2,
          "absHumidity": 9.57,
          "relHumidity": 68.2,
          "co2": 474.0
        },
        {
          "decade": 2070,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.6,
          "heatDays": 19.8,
          "tropicalNights": 39.6,
          "feltYear": 10.5,
          "feltSummer": 31.7,
          "feltWinter": 1.2,
          "absHumidity": 9.54,
          "relHumidity": 67.6,
          "co2": 473.0
        },
        {
          "decade": 2080,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.8,
          "heatDays": 25.4,
          "tropicalNights": 46.4,
          "feltYear": 10.7,
          "feltSummer": 32.1,
          "feltWinter": 1.6,
          "absHumidity": 9.95,
          "relHumidity": 69.6,
          "co2": 467.0
        },
        {
          "decade": 2090,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.9,
          "heatDays": 18.1,
          "tropicalNights": 37.0,
          "feltYear": 10.8,
          "feltSummer": 31.6,
          "feltWinter": 2.3,
          "absHumidity": 9.94,
          "relHumidity": 69.1,
          "co2": 457.0
        }
      ]
    },
    {
      "id": "대구광역시",
      "label": "대구광역시",
      "short": "대구",
      "slug": "daegu",
      "lon": 128.6,
      "lat": 35.87,
      "hasSummerFelt": true,
      "series": [
        {
          "decade": 2000,
          "scenario": "현재기후",
          "observed": true,
          "temp": 14.1,
          "heatDays": 30.8,
          "tropicalNights": 10.5,
          "feltYear": 6.66,
          "feltSummer": 30.95,
          "feltWinter": null,
          "absHumidity": 7.57,
          "relHumidity": 62.4,
          "co2": null
        },
        {
          "decade": 2010,
          "scenario": "현재기후",
          "observed": true,
          "temp": 13.9,
          "heatDays": 31.7,
          "tropicalNights": 12.2,
          "feltYear": 6.28,
          "feltSummer": 31.56,
          "feltWinter": null,
          "absHumidity": 7.79,
          "relHumidity": 65.0,
          "co2": null
        },
        {
          "decade": 2020,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.1,
          "heatDays": 42.0,
          "tropicalNights": 29.4,
          "feltYear": 7.78,
          "feltSummer": 32.51,
          "feltWinter": null,
          "absHumidity": 8.17,
          "relHumidity": 63.4,
          "co2": 414.0
        },
        {
          "decade": 2030,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.5,
          "heatDays": 45.5,
          "tropicalNights": 35.3,
          "feltYear": 8.18,
          "feltSummer": 32.96,
          "feltWinter": null,
          "absHumidity": 8.32,
          "relHumidity": 63.0,
          "co2": 440.0
        },
        {
          "decade": 2040,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.6,
          "heatDays": 53.5,
          "tropicalNights": 38.0,
          "feltYear": 8.24,
          "feltSummer": 33.49,
          "feltWinter": null,
          "absHumidity": 8.33,
          "relHumidity": 62.7,
          "co2": 458.0
        },
        {
          "decade": 2050,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.6,
          "heatDays": 51.8,
          "tropicalNights": 39.2,
          "feltYear": 8.48,
          "feltSummer": 33.56,
          "feltWinter": null,
          "absHumidity": 8.4,
          "relHumidity": 63.2,
          "co2": 469.0
        },
        {
          "decade": 2060,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.0,
          "heatDays": 52.3,
          "tropicalNights": 36.5,
          "feltYear": 8.77,
          "feltSummer": 33.51,
          "feltWinter": null,
          "absHumidity": 8.63,
          "relHumidity": 63.4,
          "co2": 474.0
        },
        {
          "decade": 2070,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.1,
          "heatDays": 55.6,
          "tropicalNights": 37.8,
          "feltYear": 8.88,
          "feltSummer": 33.62,
          "feltWinter": null,
          "absHumidity": 8.67,
          "relHumidity": 63.3,
          "co2": 473.0
        },
        {
          "decade": 2080,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.2,
          "heatDays": 58.5,
          "tropicalNights": 40.3,
          "feltYear": 8.82,
          "feltSummer": 33.88,
          "feltWinter": null,
          "absHumidity": 8.7,
          "relHumidity": 63.1,
          "co2": 467.0
        },
        {
          "decade": 2090,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.4,
          "heatDays": 59.0,
          "tropicalNights": 38.6,
          "feltYear": 9.19,
          "feltSummer": 33.82,
          "feltWinter": null,
          "absHumidity": 8.82,
          "relHumidity": 63.2,
          "co2": 457.0
        }
      ]
    },
    {
      "id": "인천광역시",
      "label": "인천광역시",
      "short": "인천",
      "slug": "incheon",
      "lon": 126.63,
      "lat": 37.46,
      "hasSummerFelt": true,
      "series": [
        {
          "decade": 2000,
          "scenario": "현재기후",
          "observed": true,
          "temp": 12.44,
          "heatDays": 5.2,
          "tropicalNights": 2.8,
          "feltYear": 5.82,
          "feltSummer": 29.1,
          "feltWinter": null,
          "absHumidity": 7.08,
          "relHumidity": 64.7,
          "co2": null
        },
        {
          "decade": 2010,
          "scenario": "현재기후",
          "observed": true,
          "temp": 12.27,
          "heatDays": 8.3,
          "tropicalNights": 8.7,
          "feltYear": 5.75,
          "feltSummer": 29.93,
          "feltWinter": null,
          "absHumidity": 7.59,
          "relHumidity": 70.1,
          "co2": null
        },
        {
          "decade": 2020,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.59,
          "heatDays": 13.7,
          "tropicalNights": 21.0,
          "feltYear": 7.13,
          "feltSummer": 30.77,
          "feltWinter": null,
          "absHumidity": 7.8,
          "relHumidity": 66.4,
          "co2": 414.0
        },
        {
          "decade": 2030,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.89,
          "heatDays": 16.8,
          "tropicalNights": 26.9,
          "feltYear": 7.52,
          "feltSummer": 31.17,
          "feltWinter": null,
          "absHumidity": 8.01,
          "relHumidity": 66.9,
          "co2": 440.0
        },
        {
          "decade": 2040,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.01,
          "heatDays": 22.2,
          "tropicalNights": 32.2,
          "feltYear": 7.64,
          "feltSummer": 31.78,
          "feltWinter": null,
          "absHumidity": 7.99,
          "relHumidity": 66.2,
          "co2": 458.0
        },
        {
          "decade": 2050,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.09,
          "heatDays": 22.5,
          "tropicalNights": 33.0,
          "feltYear": 7.79,
          "feltSummer": 31.82,
          "feltWinter": null,
          "absHumidity": 8.14,
          "relHumidity": 67.2,
          "co2": 469.0
        },
        {
          "decade": 2060,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.44,
          "heatDays": 22.4,
          "tropicalNights": 31.1,
          "feltYear": 8.15,
          "feltSummer": 31.85,
          "feltWinter": null,
          "absHumidity": 8.26,
          "relHumidity": 66.7,
          "co2": 474.0
        },
        {
          "decade": 2070,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.62,
          "heatDays": 23.1,
          "tropicalNights": 32.9,
          "feltYear": 8.38,
          "feltSummer": 31.95,
          "feltWinter": null,
          "absHumidity": 8.37,
          "relHumidity": 66.8,
          "co2": 473.0
        },
        {
          "decade": 2080,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.58,
          "heatDays": 25.6,
          "tropicalNights": 34.2,
          "feltYear": 8.29,
          "feltSummer": 32.22,
          "feltWinter": null,
          "absHumidity": 8.33,
          "relHumidity": 66.7,
          "co2": 467.0
        },
        {
          "decade": 2090,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.87,
          "heatDays": 25.0,
          "tropicalNights": 31.6,
          "feltYear": 8.59,
          "feltSummer": 32.14,
          "feltWinter": null,
          "absHumidity": 8.47,
          "relHumidity": 66.6,
          "co2": 457.0
        }
      ]
    },
    {
      "id": "광주광역시",
      "label": "광주광역시",
      "short": "광주",
      "slug": "gwangju",
      "lon": 126.85,
      "lat": 35.16,
      "hasSummerFelt": true,
      "series": [
        {
          "decade": 2000,
          "scenario": "현재기후",
          "observed": true,
          "temp": 14.13,
          "heatDays": 18.6,
          "tropicalNights": 10.0,
          "feltYear": 7.32,
          "feltSummer": 30.97,
          "feltWinter": null,
          "absHumidity": 8.4,
          "relHumidity": 69.1,
          "co2": null
        },
        {
          "decade": 2010,
          "scenario": "현재기후",
          "observed": true,
          "temp": 13.98,
          "heatDays": 24.3,
          "tropicalNights": 12.4,
          "feltYear": 7.12,
          "feltSummer": 32.21,
          "feltWinter": null,
          "absHumidity": 9.09,
          "relHumidity": 75.5,
          "co2": null
        },
        {
          "decade": 2020,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.13,
          "heatDays": 34.3,
          "tropicalNights": 31.3,
          "feltYear": 8.49,
          "feltSummer": 32.77,
          "feltWinter": null,
          "absHumidity": 9.29,
          "relHumidity": 71.9,
          "co2": 414.0
        },
        {
          "decade": 2030,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.46,
          "heatDays": 37.6,
          "tropicalNights": 38.1,
          "feltYear": 8.88,
          "feltSummer": 33.15,
          "feltWinter": null,
          "absHumidity": 9.48,
          "relHumidity": 71.9,
          "co2": 440.0
        },
        {
          "decade": 2040,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.61,
          "heatDays": 47.5,
          "tropicalNights": 41.8,
          "feltYear": 8.97,
          "feltSummer": 33.79,
          "feltWinter": null,
          "absHumidity": 9.47,
          "relHumidity": 71.2,
          "co2": 458.0
        },
        {
          "decade": 2050,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.74,
          "heatDays": 45.2,
          "tropicalNights": 42.8,
          "feltYear": 9.21,
          "feltSummer": 33.76,
          "feltWinter": null,
          "absHumidity": 9.66,
          "relHumidity": 72.1,
          "co2": 469.0
        },
        {
          "decade": 2060,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.0,
          "heatDays": 46.9,
          "tropicalNights": 40.9,
          "feltYear": 9.51,
          "feltSummer": 33.81,
          "feltWinter": null,
          "absHumidity": 9.84,
          "relHumidity": 72.3,
          "co2": 474.0
        },
        {
          "decade": 2070,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.15,
          "heatDays": 49.7,
          "tropicalNights": 41.4,
          "feltYear": 9.59,
          "feltSummer": 33.89,
          "feltWinter": null,
          "absHumidity": 9.88,
          "relHumidity": 71.9,
          "co2": 473.0
        },
        {
          "decade": 2080,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.22,
          "heatDays": 52.4,
          "tropicalNights": 44.0,
          "feltYear": 9.67,
          "feltSummer": 34.18,
          "feltWinter": null,
          "absHumidity": 9.89,
          "relHumidity": 71.7,
          "co2": 467.0
        },
        {
          "decade": 2090,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.5,
          "heatDays": 55.4,
          "tropicalNights": 43.4,
          "feltYear": 9.9,
          "feltSummer": 34.29,
          "feltWinter": null,
          "absHumidity": 10.01,
          "relHumidity": 71.3,
          "co2": 457.0
        }
      ]
    },
    {
      "id": "대전광역시",
      "label": "대전광역시",
      "short": "대전",
      "slug": "daejeon",
      "lon": 127.38,
      "lat": 36.35,
      "hasSummerFelt": true,
      "series": [
        {
          "decade": 2000,
          "scenario": "현재기후",
          "observed": true,
          "temp": 12.96,
          "heatDays": 15.6,
          "tropicalNights": 2.9,
          "feltYear": 5.68,
          "feltSummer": 30.3,
          "feltWinter": null,
          "absHumidity": 7.46,
          "relHumidity": 66.0,
          "co2": null
        },
        {
          "decade": 2010,
          "scenario": "현재기후",
          "observed": true,
          "temp": 12.82,
          "heatDays": 18.3,
          "tropicalNights": 7.1,
          "feltYear": 5.75,
          "feltSummer": 31.12,
          "feltWinter": null,
          "absHumidity": 8.0,
          "relHumidity": 71.4,
          "co2": null
        },
        {
          "decade": 2020,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.08,
          "heatDays": 32.3,
          "tropicalNights": 25.4,
          "feltYear": 6.98,
          "feltSummer": 32.0,
          "feltWinter": null,
          "absHumidity": 8.22,
          "relHumidity": 67.9,
          "co2": 414.0
        },
        {
          "decade": 2030,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.38,
          "heatDays": 33.9,
          "tropicalNights": 31.2,
          "feltYear": 7.36,
          "feltSummer": 32.36,
          "feltWinter": null,
          "absHumidity": 8.39,
          "relHumidity": 68.0,
          "co2": 440.0
        },
        {
          "decade": 2040,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.48,
          "heatDays": 42.2,
          "tropicalNights": 35.0,
          "feltYear": 7.46,
          "feltSummer": 32.93,
          "feltWinter": null,
          "absHumidity": 8.36,
          "relHumidity": 67.3,
          "co2": 458.0
        },
        {
          "decade": 2050,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.65,
          "heatDays": 40.9,
          "tropicalNights": 36.2,
          "feltYear": 7.7,
          "feltSummer": 32.97,
          "feltWinter": null,
          "absHumidity": 8.55,
          "relHumidity": 68.2,
          "co2": 469.0
        },
        {
          "decade": 2060,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.89,
          "heatDays": 42.0,
          "tropicalNights": 33.1,
          "feltYear": 8.01,
          "feltSummer": 32.93,
          "feltWinter": null,
          "absHumidity": 8.69,
          "relHumidity": 68.3,
          "co2": 474.0
        },
        {
          "decade": 2070,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.04,
          "heatDays": 43.5,
          "tropicalNights": 33.6,
          "feltYear": 8.11,
          "feltSummer": 33.06,
          "feltWinter": null,
          "absHumidity": 8.75,
          "relHumidity": 68.1,
          "co2": 473.0
        },
        {
          "decade": 2080,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.06,
          "heatDays": 46.6,
          "tropicalNights": 36.7,
          "feltYear": 8.11,
          "feltSummer": 33.35,
          "feltWinter": null,
          "absHumidity": 8.72,
          "relHumidity": 67.8,
          "co2": 467.0
        },
        {
          "decade": 2090,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.35,
          "heatDays": 47.0,
          "tropicalNights": 34.4,
          "feltYear": 8.4,
          "feltSummer": 33.33,
          "feltWinter": null,
          "absHumidity": 8.87,
          "relHumidity": 67.8,
          "co2": 457.0
        }
      ]
    },
    {
      "id": "울산광역시",
      "label": "울산광역시",
      "short": "울산",
      "slug": "ulsan",
      "lon": 129.31,
      "lat": 35.54,
      "hasSummerFelt": true,
      "series": [
        {
          "decade": 2000,
          "scenario": "현재기후",
          "observed": true,
          "temp": 14.32,
          "heatDays": 10.6,
          "tropicalNights": 5.7,
          "feltYear": 7.49,
          "feltSummer": 29.04,
          "feltWinter": null,
          "absHumidity": 7.79,
          "relHumidity": 63.4,
          "co2": null
        },
        {
          "decade": 2010,
          "scenario": "현재기후",
          "observed": true,
          "temp": 14.22,
          "heatDays": 10.5,
          "tropicalNights": 7.6,
          "feltYear": 7.4,
          "feltSummer": 29.64,
          "feltWinter": null,
          "absHumidity": 8.19,
          "relHumidity": 67.0,
          "co2": null
        },
        {
          "decade": 2020,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.3,
          "heatDays": 15.3,
          "tropicalNights": 21.1,
          "feltYear": 8.7,
          "feltSummer": 30.53,
          "feltWinter": null,
          "absHumidity": 8.52,
          "relHumidity": 65.3,
          "co2": 414.0
        },
        {
          "decade": 2030,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.69,
          "heatDays": 18.7,
          "tropicalNights": 27.7,
          "feltYear": 9.1,
          "feltSummer": 31.08,
          "feltWinter": null,
          "absHumidity": 8.67,
          "relHumidity": 64.9,
          "co2": 440.0
        },
        {
          "decade": 2040,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.82,
          "heatDays": 22.5,
          "tropicalNights": 31.4,
          "feltYear": 9.23,
          "feltSummer": 31.53,
          "feltWinter": null,
          "absHumidity": 8.66,
          "relHumidity": 64.3,
          "co2": 458.0
        },
        {
          "decade": 2050,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 15.95,
          "heatDays": 22.5,
          "tropicalNights": 32.8,
          "feltYear": 9.39,
          "feltSummer": 31.54,
          "feltWinter": null,
          "absHumidity": 8.81,
          "relHumidity": 64.9,
          "co2": 469.0
        },
        {
          "decade": 2060,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.12,
          "heatDays": 21.0,
          "tropicalNights": 28.3,
          "feltYear": 9.65,
          "feltSummer": 31.51,
          "feltWinter": null,
          "absHumidity": 8.92,
          "relHumidity": 65.0,
          "co2": 474.0
        },
        {
          "decade": 2070,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.31,
          "heatDays": 22.3,
          "tropicalNights": 31.8,
          "feltYear": 9.83,
          "feltSummer": 31.63,
          "feltWinter": null,
          "absHumidity": 9.01,
          "relHumidity": 64.9,
          "co2": 473.0
        },
        {
          "decade": 2080,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.31,
          "heatDays": 24.6,
          "tropicalNights": 34.4,
          "feltYear": 9.77,
          "feltSummer": 31.85,
          "feltWinter": null,
          "absHumidity": 8.98,
          "relHumidity": 64.7,
          "co2": 467.0
        },
        {
          "decade": 2090,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 16.58,
          "heatDays": 21.3,
          "tropicalNights": 30.7,
          "feltYear": 10.15,
          "feltSummer": 31.75,
          "feltWinter": null,
          "absHumidity": 9.16,
          "relHumidity": 65.0,
          "co2": 457.0
        }
      ]
    },
    {
      "id": "세종특별자치시",
      "label": "세종특별자치시",
      "short": "세종",
      "slug": "sejong",
      "lon": 127.29,
      "lat": 36.48,
      "hasSummerFelt": true,
      "series": [
        {
          "decade": 2000,
          "scenario": "현재기후",
          "observed": true,
          "temp": 12.24,
          "heatDays": 11.5,
          "tropicalNights": 0.8,
          "feltYear": 4.63,
          "feltSummer": 30.04,
          "feltWinter": null,
          "absHumidity": 7.2,
          "relHumidity": 66.6,
          "co2": null
        },
        {
          "decade": 2010,
          "scenario": "현재기후",
          "observed": true,
          "temp": 12.3,
          "heatDays": 18.5,
          "tropicalNights": 3.4,
          "feltYear": 4.72,
          "feltSummer": 31.16,
          "feltWinter": null,
          "absHumidity": 7.77,
          "relHumidity": 71.6,
          "co2": null
        },
        {
          "decade": 2020,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.48,
          "heatDays": 30.9,
          "tropicalNights": 20.4,
          "feltYear": 5.93,
          "feltSummer": 31.9,
          "feltWinter": null,
          "absHumidity": 7.96,
          "relHumidity": 68.2,
          "co2": 414.0
        },
        {
          "decade": 2030,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.76,
          "heatDays": 31.4,
          "tropicalNights": 26.1,
          "feltYear": 6.34,
          "feltSummer": 32.17,
          "feltWinter": null,
          "absHumidity": 8.12,
          "relHumidity": 68.4,
          "co2": 440.0
        },
        {
          "decade": 2040,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.88,
          "heatDays": 40.0,
          "tropicalNights": 30.2,
          "feltYear": 6.45,
          "feltSummer": 32.74,
          "feltWinter": null,
          "absHumidity": 8.11,
          "relHumidity": 67.8,
          "co2": 458.0
        },
        {
          "decade": 2050,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.02,
          "heatDays": 38.9,
          "tropicalNights": 30.7,
          "feltYear": 6.66,
          "feltSummer": 32.82,
          "feltWinter": null,
          "absHumidity": 8.28,
          "relHumidity": 68.6,
          "co2": 469.0
        },
        {
          "decade": 2060,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.27,
          "heatDays": 39.8,
          "tropicalNights": 27.2,
          "feltYear": 6.95,
          "feltSummer": 32.8,
          "feltWinter": null,
          "absHumidity": 8.41,
          "relHumidity": 68.6,
          "co2": 474.0
        },
        {
          "decade": 2070,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.42,
          "heatDays": 41.3,
          "tropicalNights": 27.4,
          "feltYear": 7.06,
          "feltSummer": 32.93,
          "feltWinter": null,
          "absHumidity": 8.47,
          "relHumidity": 68.5,
          "co2": 473.0
        },
        {
          "decade": 2080,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.46,
          "heatDays": 43.9,
          "tropicalNights": 31.2,
          "feltYear": 7.03,
          "feltSummer": 33.2,
          "feltWinter": null,
          "absHumidity": 8.46,
          "relHumidity": 68.2,
          "co2": 467.0
        },
        {
          "decade": 2090,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.73,
          "heatDays": 44.0,
          "tropicalNights": 28.6,
          "feltYear": 7.36,
          "feltSummer": 33.16,
          "feltWinter": null,
          "absHumidity": 8.61,
          "relHumidity": 68.3,
          "co2": 457.0
        }
      ]
    },
    {
      "id": "제주특별자치도",
      "label": "제주특별자치도",
      "short": "제주",
      "slug": "jeju",
      "lon": 126.53,
      "lat": 33.5,
      "hasSummerFelt": true,
      "series": [
        {
          "decade": 2000,
          "scenario": "현재기후",
          "observed": true,
          "temp": 16.13,
          "heatDays": 3.6,
          "tropicalNights": 21.6,
          "feltYear": 10.19,
          "feltSummer": 29.52,
          "feltWinter": null,
          "absHumidity": 9.4,
          "relHumidity": 68.5,
          "co2": null
        },
        {
          "decade": 2010,
          "scenario": "현재기후",
          "observed": true,
          "temp": 16.05,
          "heatDays": 6.1,
          "tropicalNights": 23.9,
          "feltYear": 10.53,
          "feltSummer": 30.06,
          "feltWinter": null,
          "absHumidity": 10.28,
          "relHumidity": 75.3,
          "co2": null
        },
        {
          "decade": 2020,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 17.04,
          "heatDays": 7.2,
          "tropicalNights": 39.2,
          "feltYear": 11.56,
          "feltSummer": 30.81,
          "feltWinter": null,
          "absHumidity": 10.46,
          "relHumidity": 72.2,
          "co2": 414.0
        },
        {
          "decade": 2030,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 17.41,
          "heatDays": 12.2,
          "tropicalNights": 46.7,
          "feltYear": 11.95,
          "feltSummer": 31.29,
          "feltWinter": null,
          "absHumidity": 10.64,
          "relHumidity": 71.8,
          "co2": 440.0
        },
        {
          "decade": 2040,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 17.54,
          "heatDays": 16.1,
          "tropicalNights": 51.2,
          "feltYear": 12.11,
          "feltSummer": 31.77,
          "feltWinter": null,
          "absHumidity": 10.68,
          "relHumidity": 71.5,
          "co2": 458.0
        },
        {
          "decade": 2050,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 17.69,
          "heatDays": 16.7,
          "tropicalNights": 51.6,
          "feltYear": 12.28,
          "feltSummer": 31.75,
          "feltWinter": null,
          "absHumidity": 10.84,
          "relHumidity": 71.9,
          "co2": 469.0
        },
        {
          "decade": 2060,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 17.9,
          "heatDays": 16.4,
          "tropicalNights": 51.1,
          "feltYear": 12.58,
          "feltSummer": 31.87,
          "feltWinter": null,
          "absHumidity": 10.99,
          "relHumidity": 72.0,
          "co2": 474.0
        },
        {
          "decade": 2070,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 18.03,
          "heatDays": 16.7,
          "tropicalNights": 52.3,
          "feltYear": 12.72,
          "feltSummer": 31.84,
          "feltWinter": null,
          "absHumidity": 11.03,
          "relHumidity": 71.7,
          "co2": 473.0
        },
        {
          "decade": 2080,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 18.18,
          "heatDays": 18.7,
          "tropicalNights": 56.3,
          "feltYear": 12.85,
          "feltSummer": 32.18,
          "feltWinter": null,
          "absHumidity": 11.13,
          "relHumidity": 71.7,
          "co2": 467.0
        },
        {
          "decade": 2090,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 18.32,
          "heatDays": 15.7,
          "tropicalNights": 54.4,
          "feltYear": 13.03,
          "feltSummer": 32.07,
          "feltWinter": null,
          "absHumidity": 11.23,
          "relHumidity": 71.8,
          "co2": 457.0
        }
      ]
    },
    {
      "id": "강원 속초시",
      "label": "강원 속초시",
      "short": "속초",
      "slug": "sokcho",
      "lon": 128.59,
      "lat": 38.21,
      "hasSummerFelt": true,
      "series": [
        {
          "decade": 2000,
          "scenario": "현재기후",
          "observed": true,
          "temp": 12.4,
          "heatDays": 5.2,
          "tropicalNights": 2.8,
          "feltYear": 5.4,
          "feltSummer": 27.2,
          "feltWinter": -4.3,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null
        },
        {
          "decade": 2010,
          "scenario": "현재기후",
          "observed": true,
          "temp": 12.6,
          "heatDays": 8.4,
          "tropicalNights": 6.1,
          "feltYear": 6.1,
          "feltSummer": 28.2,
          "feltWinter": -3.9,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null
        },
        {
          "decade": 2020,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.6,
          "heatDays": 7.5,
          "tropicalNights": 11.7,
          "feltYear": 7.0,
          "feltSummer": 29.0,
          "feltWinter": -2.8,
          "absHumidity": 7.58,
          "relHumidity": 64.4,
          "co2": 414.0
        },
        {
          "decade": 2030,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.1,
          "heatDays": 7.6,
          "tropicalNights": 15.4,
          "feltYear": 7.5,
          "feltSummer": 29.4,
          "feltWinter": -1.9,
          "absHumidity": 7.51,
          "relHumidity": 61.9,
          "co2": 440.0
        },
        {
          "decade": 2040,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.2,
          "heatDays": 11.8,
          "tropicalNights": 21.5,
          "feltYear": 7.6,
          "feltSummer": 29.9,
          "feltWinter": -2.4,
          "absHumidity": 8.06,
          "relHumidity": 66.0,
          "co2": 458.0
        },
        {
          "decade": 2050,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.1,
          "heatDays": 9.4,
          "tropicalNights": 16.8,
          "feltYear": 7.5,
          "feltSummer": 29.9,
          "feltWinter": -2.7,
          "absHumidity": 8.15,
          "relHumidity": 67.2,
          "co2": 469.0
        },
        {
          "decade": 2060,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.5,
          "heatDays": 9.4,
          "tropicalNights": 18.6,
          "feltYear": 8.1,
          "feltSummer": 30.0,
          "feltWinter": -1.9,
          "absHumidity": 8.46,
          "relHumidity": 68.1,
          "co2": 474.0
        },
        {
          "decade": 2070,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.7,
          "heatDays": 8.3,
          "tropicalNights": 16.9,
          "feltYear": 8.3,
          "feltSummer": 30.1,
          "feltWinter": -1.8,
          "absHumidity": 8.44,
          "relHumidity": 67.1,
          "co2": 473.0
        },
        {
          "decade": 2080,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.8,
          "heatDays": 13.3,
          "tropicalNights": 24.7,
          "feltYear": 8.3,
          "feltSummer": 30.5,
          "feltWinter": -1.6,
          "absHumidity": 8.77,
          "relHumidity": 69.3,
          "co2": 467.0
        },
        {
          "decade": 2090,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.9,
          "heatDays": 6.8,
          "tropicalNights": 14.0,
          "feltYear": 8.5,
          "feltSummer": 29.9,
          "feltWinter": -0.8,
          "absHumidity": 8.83,
          "relHumidity": 69.3,
          "co2": 457.0
        }
      ]
    },
    {
      "id": "충청남도 천안시",
      "label": "충청남도 천안시",
      "short": "천안",
      "slug": "cheonan",
      "lon": 127.15,
      "lat": 36.82,
      "hasSummerFelt": false,
      "series": [
        {
          "decade": 2000,
          "scenario": "현재기후",
          "observed": true,
          "temp": 12.0,
          "heatDays": 10.0,
          "tropicalNights": 0.8,
          "feltYear": 4.5,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null,
          "note": "이미지 추정값"
        },
        {
          "decade": 2010,
          "scenario": "현재기후",
          "observed": true,
          "temp": 12.3,
          "heatDays": 16.5,
          "tropicalNights": 4.2,
          "feltYear": 4.9,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": null,
          "relHumidity": null,
          "co2": null,
          "note": "이미지 추정값"
        },
        {
          "decade": 2020,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.3,
          "heatDays": 28.4,
          "tropicalNights": 21.2,
          "feltYear": 6.0,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": 7.98,
          "relHumidity": 69.1,
          "co2": 414.0,
          "note": "이미지 추정값"
        },
        {
          "decade": 2030,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.7,
          "heatDays": 31.1,
          "tropicalNights": 25.4,
          "feltYear": 6.4,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": 7.95,
          "relHumidity": 67.2,
          "co2": 440.0,
          "note": "이미지 추정값"
        },
        {
          "decade": 2040,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.8,
          "heatDays": 37.9,
          "tropicalNights": 31.0,
          "feltYear": 6.5,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": 8.42,
          "relHumidity": 70.7,
          "co2": 458.0,
          "note": "이미지 추정값"
        },
        {
          "decade": 2050,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 13.7,
          "heatDays": 35.3,
          "tropicalNights": 28.4,
          "feltYear": 6.5,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": 8.55,
          "relHumidity": 72.2,
          "co2": 469.0,
          "note": "이미지 추정값"
        },
        {
          "decade": 2060,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.2,
          "heatDays": 38.5,
          "tropicalNights": 28.6,
          "feltYear": 7.0,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": 8.87,
          "relHumidity": 72.7,
          "co2": 474.0,
          "note": "이미지 추정값"
        },
        {
          "decade": 2070,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.3,
          "heatDays": 39.2,
          "tropicalNights": 27.0,
          "feltYear": 7.0,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": 8.94,
          "relHumidity": 72.8,
          "co2": 473.0,
          "note": "이미지 추정값"
        },
        {
          "decade": 2080,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.4,
          "heatDays": 42.8,
          "tropicalNights": 33.8,
          "feltYear": 7.3,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": 9.28,
          "relHumidity": 75.1,
          "co2": 467.0,
          "note": "이미지 추정값"
        },
        {
          "decade": 2090,
          "scenario": "SSP1-2.6",
          "observed": false,
          "temp": 14.5,
          "heatDays": 40.1,
          "tropicalNights": 25.4,
          "feltYear": 7.3,
          "feltSummer": null,
          "feltWinter": null,
          "absHumidity": 9.32,
          "relHumidity": 75.0,
          "co2": 457.0,
          "note": "이미지 추정값"
        }
      ]
    }
  ]
};

if (typeof module !== "undefined" && module.exports) {
    module.exports = SEARCH_DATA;
}
